tap "homebrew/bundle"
tap "homebrew/services"

# Core
brew "openssl@3"
brew "wget"
brew "telnet"
brew "jq"
brew "yq"
brew "gawk"

# Programming Languages
brew "openjdk@17"
brew "python@3.11"
# brew "go" # installing with version manager instead
brew "node"
brew "yarn"

# Tools
brew "podman"
brew "hugo"
brew "neovim"
brew "thefuck"

brew "git-recent"
brew "git-secret"
brew "protobuf"

# Kubernetes
tap "fluxcd/tap/flux"

brew "kubectl"
brew "kubectx"
brew "helm"

brew "k9s"
brew "kind"
brew "operator-sdk"

# Cloud Providers
tap "hashicorp/tap"

brew "awscli"
brew "eksctl"
brew "hashicorp/tap/terraform"
